name: Local CI Demo

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest
      - name: Build Docker image
        run: docker build -t cats-dogs-mlops .

  smoke-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Create sample image
        run: |
          mkdir -p tests
          echo "" > tests/sample.jpg
      - name: Start service with Docker Compose
        run: docker-compose up -d
      - name: Wait for service
        run: |
          for i in {1..10}; do
            curl -sf http://localhost:8000/health && break
            sleep 3
          done
      - name: Smoke test /health
        run: curl -f http://localhost:8000/health
      - name: Smoke test /predict
        run: |
          curl -f -X POST "http://localhost:8000/predict" -F "file=@tests/sample.jpg" || exit 1
